version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
    networks:
      - sampleapp-network
  mongo-seed:
    container_name: mongo-seed
    build:
      context: ./.docker/mongo-seed
    networks:
      - sampleapp-network
  mvc:
    container_name: mvc
    image: sample-app-mvc
    build:
      context: ./SampleApp.MVC/
    depends_on:
      - api
      - mongo
    ports:
      - "8080:80"
    env_file:
      - ./.docker/env/mvc.${APP_ENV}.env
    networks:
      - sampleapp-network
  api:
    container_name: api
    image: sample-app-api
    build:
      context: ./SampleApp.API/
    ports:
      - "8090:80"
    networks:
      - sampleapp-network
  hoverfly:
    container_name: hoverfly
    build:
      context: ./.docker/hoverfly
    volumes:
      - /c/users/thoma/source/repos/SampleApp/.docker/hoverfly/simulations:/data # bind mount absolute path on local machine
    ports:
      - "8888:8888"
      - "8500:8500"
    networks:
      - sampleapp-network
  # mock-api:
  #   container_name: mock-api
  #   image: node:11
  #   build:
  #     context: ./.docker/json-server/
  #   ports:
  #     - "8030:80"
  #   networks:
  #     - sampleapp-network
networks:
  sampleapp-network:
    driver: bridge